### PR TITLE
resolve archetype_details properly in AQL

### PR DESCRIPTION
**Pull request by chevalleyc**
## Changes

support aql: `c/archetype_details` and attributes.

## Related issue

Fixes: https://github.com/ehrbase/project_management/issues/464

## Additional information and checks

- [ ] Pull request linked in changelog

### CODE REVIEW

**Review by wlad — CHANGES_REQUESTED** [review]
I can't confirm the issue is fixed. I'm getting `"rows": []` as result

**Comment by chevalleyc** [comment]
I've tested this branch on my system:

```

{
"q": "select c/archetype_details
		from EHR e[ehr_id/value = '068076a6-aaa8-4ce6-95e2-c78df3c79dc6']
		contains composition c[openEHR-EHR-COMPOSITION.test_all_types.v1]
		contains observation o[openEHR-EHR-OBSERVATION.test_all_types.v1]
		WHERE c/uid/value = 'e312b9c1-15c4-4884-9f5f-9323d2fbd97b'"
}
```
result:
```
{
    "q": "select c/archetype_details\n\t\tfrom EHR e[ehr_id/value = '068076a6-aaa8-4ce6-95e2-c78df3c79dc6']\n\t\tcontains composition c[openEHR-EHR-COMPOSITION.test_all_types.v1]\n\t\tcontains observation o[openEHR-EHR-OBSERVATION.test_all_types.v1]\n\t\tWHERE c/uid/value = 'e312b9c1-15c4-4884-9f5f-9323d2fbd97b'",
    "columns": [
        {
            "path": "/archetype_details",
            "name": "#0"
        }
    ],
    "rows": [
        [
            {
                "_type": "ARCHETYPED",
                "rm_version": "1.0.4",
                "template_id": {
                    "_type": "TEMPLATE_ID",
                    "value": "test_all_types.en.v1"
                },
                "archetype_id": {
                    "_type": "ARCHETYPE_ID",
                    "value": "openEHR-EHR-COMPOSITION.test_all_types.v1"
                }
            }
        ]
    ]
}
```
@wlad what did you exactly do to get an empty result? Thanks!

**Comment by ppazos** [comment]
@chevalleyc I'm talking to Wlad, he is having issues trying to get the result you posted. Can you share the composition you loaded to get that result?

**Comment by chevalleyc** [comment]
I have tested this query with the latest code base and it returns the result as expected:

```
{
    "q": "SELECT c/archetype_details from EHR e CONTAINS composition c where c/uid/value = 'd17b9883-8ac9-4a32-9d7c-dfb7ab4058ca'",
    "columns": [
        {
            "path": "/archetype_details",
            "name": "#0"
        }
    ],
    "rows": [
        [
            {
                "_type": "ARCHETYPED",
                "rm_version": "1.1.4",
                "template_id": {
                    "_type": "TEMPLATE_ID",
                    "value": "Laborbefund"
                },
                "archetype_id": {
                    "_type": "ARCHETYPE_ID",
                    "value": "openEHR-EHR-COMPOSITION.report-result.v1"
                }
            }
        ]
    ]
}
```

**Pull request closed without merging**
