### PR TITLE
#14 add example generator to openehr and ecis template rest resources

### PR DESCRIPTION
**Pull request by HolgerReiseVSys**
## Changes

- First change

## Additional information and checks

- [ ] Pull request linked in changelog

### CODE REVIEW

**Comment by birgerhaarbrandt** [comment]
EHRbase does not seem to support all codes from ISO_639-1. Your default "aa" is rejected by EHRbase during validation.

**Comment by birgerhaarbrandt** [comment]
I also had to remove one line 

`responseData.setFormat(format);`

within Template Controller class to be able to build

**Comment by birgerhaarbrandt** [comment]
blanks in template name or template id cause an internal error (500)

**Comment by birgerhaarbrandt** [comment]
generation of the URL as part of the response body is wrong:

```
 "meta": {
        "href": {
            "url": "http://localhost:8080/ehrbase/rest/ecis/v1/template/Station%C3%A4rer_Versorgungsfall/example?format=FLAT/rest/ecis/v1/templateStationärer_Versorgungsfall/example"
        }
    },
```

**Comment by sidharthramesh** [comment]
Hey @birgerhaarbrandt and @HolgerReiseVSys can you give a rough estimate on when this example endpoints feature will be completed?

I’m creating a course on openEHR and using EHRbase to demonstrate most of the functionality. Having a lesson on using the example endpoint would be great since it’s the easiest for new comers to get a working composition.

There are other tools, but they are not very reliable.

**Comment by birgerhaarbrandt** [comment]
I found a case which might require some improvement. Please find attached an OPT that contains terminology references:

[GECCO_Laborbefund.opt.zip](https://github.com/ehrbase/ehrbase/files/8402829/GECCO_Laborbefund.opt.zip)

This will produce results like this:

```
        "laborbefund/laborergebnis:0/pro_laboranalyt:0/interpretation|value": "No example for termínology '//fhir.hl7.org/ValueSet/$expand?url=http://hl7.org/fhir/ValueSet/observation-interpretation' available",
        "laborbefund/laborergebnis:0/pro_laboranalyt:0/interpretation|terminology": "//fhir.hl7.org/ValueSet/$expand?url=http://hl7.org/fhir/ValueSet/observation-interpretation",
```

While the example "works" as long as terminology validation through an external server is deactivated, we can consider resolving the external reference in EHRbase. This should not be in the scope of this PR, but should serve as reminder to have a discussion about the idea.

**Comment by birgerhaarbrandt** [comment]
Please find attached the following template "Mikrobiologischer Befund":
[Mikrobiologischer Befund-3.opt.zip](https://github.com/ehrbase/ehrbase/files/8404148/Mikrobiologischer.Befund-3.opt.zip)

When trying to store the created example as FLAT, I get the following error:

```
{
    "error": "Bad Request",
    "message": "/content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1 and name/value='Befund']/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_panel.v0 and name/value='Kultur']/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1 and name/value='Pro Erreger']/items[openEHR-EHR-CLUSTER.erregerdetails.v1]/items[at0035]/null_flavour: Attribute has 0 occurrences, but must be 1..1"
}
```

The example with STRUCTURED Format produces following error message:

```
{
    "error": "Bad Request",
    "message": "Could not consume Parts [mikrobiologischer_befund]"
}

```

**Comment by stefanspiska** [comment]
@sidharthramesh 
I will try to have a look this week.

There will be however some templates the example generate will not be able to generate valide examples.

**Comment by sidharthramesh** [comment]
I see that the CompositionFormat enum has FLAT, STRUCTURED, RAW, XML, ECISFLAT, EXPANDED, JSON. This reflects in the Swagger UI.

On trying the following formats on the example endpoint:
- RAW
- ECISFLAT
- EXPANDED

Getting this error:
```json
{
	"error": "Internal Server Error",
	"message": "An internal error has occurred. Please contact your administrator."
}
```

Server logs:
```
org.ehrbase.api.exception.UnexpectedSwitchCaseException: Unexpected value of CompositionFormat: 'RAW'
        at org.ehrbase.service.CompositionServiceImp.serialize(CompositionServiceImp.java:516)
        at org.ehrbase.service.CompositionServiceImp$$FastClassBySpringCGLIB$$9bcfd210.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
...
```

**Comment by sidharthramesh** [comment]
Tried a few of our templates. Mostly seems to be working after replacing the language and country codes! 

Also I noticed that by default, the composer is set to:
```json
{
 "ctx/composer_self": true
}
```

I'm not sure what this means, but after looking at the [documentation here](https://docs.ehrbase.org/en/latest/09_flat/02_context/index.html#composer-composer-name-composer-id-composer-self), I am assuming its a reference to the patient?

Don't you think it should also have other attributes so that the users can populate the composer details if they want later?
For eg:
```json
{
 "ctx/composer_name": "Silvia Blake",
 "ctx/composer_id": "123",
 "ctx/id_namespace": "HOSPITAL-NS",
 "ctx/id_scheme": "HOSPITAL-NS"
}
```

**Comment by sidharthramesh** [comment]
Regarding the API itself:

Any plans on adopting the `exampleFilter` query param that Better CDR has been using? 
- Possible values: `INPUT, OUTPUT`. 
- `INPUT` will get all of the context information in `ctx/*` attributes. 
- `OUTPUT` will get them populated within the composition. 
- As of now, it seems like only the composer get populated within ctx, and everything else is within the composition.

Any plans on adopting the `random` query parameter that EHR.DB [has been using](https://db.ehr.solutions/cloud/?urls.primaryName=EHRDB%20API#/template/getTemplateExampleByIdUsingGET) to generate random compositions? 
Related issue: https://github.com/ehrbase/openEHR_SDK/issues/348
- Possibile values: `NONE, VALUES, STRUCTURE, ALL`.
- `NONE` will not randomize.
- `VALUES` will randomize the values.
- `STRUCTURE` will output random, but valid composition structures.
- `ALL` will randomize both.

**Comment by stefanspiska** [comment]
@birgerhaarbrandt @sidharthramesh 

I updated the pr.
 now:

-  it builds
- directly returns the example composition like better
- Language & composer are now fixed.
-  i could not reproduce the issue with spaces in the template name with Postman. maybe postman automatically escapes spaces as it should be done

For everything else please create bug or enhancement tickets.

**Review by stefanspiska — APPROVED** [review]

**Pull request merged**
