### PR TITLE
Feature/466 verbose interval

### PR DESCRIPTION
**Pull request by chevalleyc**
## Changes
several fixes when rendering interval in AQL query.

## Additional information and checks

- [ ] Pull request linked in changelog

### CODE REVIEW

**Comment by wlad** [comment]
@chevalleyc  is this related to any existing issue or test?

**Comment by birgerhaarbrandt** [comment]
@chevalleyc can you please provide some description what was not represented correctly and what has been fixed?

**Comment by chevalleyc** [comment]
The canonical representation of interval was not properly formatted or missing. with this fix, you can query interval content

**Comment by birgerhaarbrandt** [comment]
What example compositions and templates did you use?

**Comment by chevalleyc** [comment]
I have been using Pablo's all types composition. I have/will provide tests for this as part of the new systematic test framework

**Comment by birgerhaarbrandt** [comment]
Checked with the following test scripts and got the following result:

[Intervalle AQL Test.postman_collection.zip](https://github.com/ehrbase/ehrbase/files/6077611/Intervalle.AQL.Test.postman_collection.zip)

```
    "columns": [
        {
            "path": "/encoding",
            "name": "#0"
        },
        {
            "path": "/language",
            "name": "#1"
        },
        {
            "path": "/other_participations",
            "name": "#2"
        },
        {
            "path": "/data[at0001]/events[at0002]/data[at0003]/items[at0004]",
            "name": "#3"
        },
        {
            "path": "/data[at0001]/events[at0002]/data[at0003]/items[at0006]",
            "name": "#4"
        },
        {
            "path": "/data[at0001]/events[at0002]/data[at0003]/items[at0005]/value/upper",
            "name": "#5"
        },
        {
            "path": "/data[at0001]/events[at0002]/time",
            "name": "#6"
        },
        {
            "path": "/data[at0001]/origin",
            "name": "#7"
        }
    ],
    "rows": []
```

**Comment by birgerhaarbrandt** [comment]
Nevermind, the issue came from the "other_participation" column (we need to create an issue for this as well). Otherwise, I found some things:

```
{

"q": "select
    a_a/data[at0001]/events[at0002]/data[at0003]/items[at0006]
from EHR e
contains COMPOSITION a
contains OBSERVATION a_a[openEHR-EHR-OBSERVATION.intervalls.v0]"

}
```

Result Set in EHRSCAPE:

```
 "rows": [
    [
      {
        "_type": "ELEMENT",
        "name": {
          "_type": "DV_TEXT",
          "value": "Zeitintervall"
        },
        "archetype_node_id": "at0006",
        "value": {
          "_type": "DV_INTERVAL",
          "lower": {
            "_type": "DV_DATE_TIME",
            "value": "2021-03-03T17:16:33.064098+01:00"
          },
          "upper": {
            "_type": "DV_DATE_TIME",
            "value": "2021-03-03T17:16:33.064029+01:00"
          },
          "lower_unbounded": false,
          "upper_unbounded": false
        }
      }
    ]
```

Vs Result Set in EHRbase

```
 "rows": [
        [
            {
                "name": {
                    "value": "Zeitintervall",
                    "_type": "DV_TEXT"
                },
                "value": {
                    "lower": {
                        "value": "2021-03-03T17:16:33.064098+01:00",
                        "epoch_offset": 1.614788193E9,
                        "_type": "DV_DATE_TIME"
                    },
                    "upper": {
                        "value": "2021-03-03T17:16:33.064029+01:00",
                        "epoch_offset": 1.614788193E9,
                        "_type": "DV_DATE_TIME"
                    },
                    "lower_included": true,
                    "upper_included": true,
                    "lower_unbounded": false,
                    "upper_unbounded": false,
                    "_type": "DV_INTERVAL<DV_DATE_TIME>"
                },
                "_type": "ELEMENT"
            }
        ]
    ]
```

My findings: 
-"archetype_node_id": "at0006" is missing in EHRbase
-epoch_offset is something that should be removed?
-I think we are correct regading the "included" fields
- "_type": "DV_INTERVAL<DV_DATE_TIME>" is missing on their end

**Comment by birgerhaarbrandt** [comment]
I also tested the behavior with DV_INTERVAL<DV_QUANTITY> and DV_INTERVAL<DV_COUNT> and have consistent differences as reported above.

**Comment by birgerhaarbrandt** [comment]
@chevalleyc I checked the test query with the feature/510_error_in_processing_OR branch (by accident) and it looks like all these things mentioned here have been resolved? Has this been part of the bigger sync PR? I'm a bit confused to be honest

**Comment by chevalleyc** [comment]
yes you are right, this has been fixed as part of the bulk fix, the previous format was conflicting when comparing it with Archie marshalling. Thanks!

**Pull request closed without merging**
