### PR TITLE
Feature/205 ehr timezone

### PR DESCRIPTION
**Pull request by chevalleyc**
## Changes

normalize time offset in DvDateTime canonical representation (was either missing or was a time zone) for ehr/time_created

## Related issue

fixes: https://github.com/ehrbase/project_management/issues/205

## Additional information and checks

- [ ] Pull request linked in changelog

### CODE REVIEW

**Comment by jakesmolka** [comment]
Does this by any chance also fix https://github.com/ehrbase/project_management/issues/453 (`,` problem)? I don't have time to check it myself right now, sorry.

**Comment by chevalleyc** [comment]
> Does this by any chance also fix [ehrbase/project_management#453](https://github.com/ehrbase/project_management/issues/453) (`,` problem)? I don't have time to check it myself right now, sorry.

yes, but it doesn't deal with the locale dependent representation, only the time offset here.

**Comment by wlad** [comment]
@jakesmolka 
> Does this by any chance also fix ehrbase/project_management#453 (, problem)? I don't have time to check it myself right now, sorry.

No, POST /ehr still has a comma in time_created timestamp

**Review by wlad — CHANGES_REQUESTED** [review]
missing milliseconds cause a diff that makes the tests fail

```
# on CI
actual: 2021-02-09T14:43:43Z
expected: 2021-02-09T14:43:43.767Z

# on my local machine
actual: 2021-02-09T15:36:16+01:00
expected: 2021-02-09T15:36:16.987+01:00
```

**Review by wlad — APPROVED** [review]
tests pass

bug traces removed

**Pull request merged**
