### PR TITLE
refactors PR 232 for DvCodedText.mappings

### PR DESCRIPTION
**Pull request by chevalleyc**
## Changes

Refactored PR #232 and fixed some minor bugs.

The changes impact the DB structure (entry.category & event_context.setting are now cast as UDT ehr.dv_coded_text). A migration (V35) implements the required DB changes.

The following is now supported in CRUD and AQL:

### composition/category

```
  "category": {
    "_type": "DV_CODED_TEXT",
    "value": "event",
    "defining_code": {
      "terminology_id": {
        "value": "openehr"
      },
      "code_string": "433"
    },
    "mappings": {
      "_type": "TERM_MAPPING",
      "match": "=",
      "purpose": {
        "_type": "DV_CODED_TEXT",
        "value": "Erfasst",
        "defining_code": {
          "terminology_id": {
            "value": "local"
          },
          "code_string": "irgendein Purpose"
        }
      },
      "target": {
        "terminology_id": {
          "value": "SNOMED-CT"
        },
        "code_string": "345356676789"
      }
    }
  },
```

### composition/contex/setting

```
    "setting": {
      "_type": "DV_CODED_TEXT",
      "value": "other care",
      "defining_code": {
        "terminology_id": {
          "value": "openehr"
        },
        "code_string": "238"
      },
      "mappings": {
        "_type": "TERM_MAPPING",
        "match": "=",
        "purpose": {
          "_type": "DV_CODED_TEXT",
          "value": "Erfasst",
          "defining_code": {
            "terminology_id": {
              "value": "local"
            },
            "code_string": "irgendein Purpose"
          }
        },
        "target": {
          "terminology_id": {
            "value": "SNOMED-CT"
          },
          "code_string": "345356676789"
        }
      }
    },
```

### Any DvCodedText in Composition/content

```
                    {
                      "_type": "ELEMENT",
                      "name": {
                        "_type": "DV_TEXT",
                        "value": "Probenart"
                      },
                      "value": {
                        "_type": "DV_TEXT",
                        "value": "Blut",
                        "mappings": {
                          "_type": "TERM_MAPPING",
                          "match": "=",
                          "purpose": {
                            "_type": "DV_CODED_TEXT",
                            "value": "Erfasst",
                            "defining_code": {
                              "terminology_id": {
                                "value": "local"
                              },
                              "code_string": "irgendein Purpose"
                            }
                          },
                          "target": {
                            "terminology_id": {
                              "value": "SNOMED-CT"
                            },
                            "code_string": "345356676789"
                          }
                        }
                      },
                      "archetype_node_id": "at0029"
                    },
```
### AQL
```
{
  "q":"select
c/category/mappings/match
from EHR e
contains COMPOSITION c
where c/uid/value = 'e8cc8ad5-42bd-4e81-b46b-96d030a49ea9'
"
}

```
In a content:
```
{
  "q":"select
c/content[openEHR-EHR-OBSERVATION.laboratory_test_result.v1]/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0029]/value/mappings/target/code_string
from EHR e
contains COMPOSITION c
where c/uid/value = '04d4d9cb-b02e-487e-b8df-c41f5b4d7bf5'
"
}
```

## Related issue

See PR #232 

fixes: CR ehrbase/project_management#226

see also: https://github.com/ehrbase/openEHR_SDK/pull/96

## Additional information and checks

- [ ] Pull request linked in changelog

### CODE REVIEW

**Review by birgerhaarbrandt — CHANGES_REQUESTED** [review]
I found that the following query

```
{
  "q": "SELECT c FROM EHR e CONTAINS COMPOSITION c WHERE c/context/setting/mappings/purpose/value = 'Erfasst'" 
} 
```

creates the following error message

```
{
    "error": "Could not roll back JDBC transaction; nested exception is java.sql.SQLException: Connection is closed",
    "status": "Internal Server Error"
}
```

**Comment by chevalleyc** [comment]
> I found that the following query
> 
> ```
> {
>   "q": "SELECT c FROM EHR e CONTAINS COMPOSITION c WHERE c/context/setting/mappings/purpose/value = 'Erfasst'" 
> } 
> ```
> 
> creates the following error message
> 
> ```
> {
>     "error": "Could not roll back JDBC transaction; nested exception is java.sql.SQLException: Connection is closed",
>     "status": "Internal Server Error"
> }
> ```

Actually this issue was mentioned in the original PR https://github.com/ehrbase/ehrbase/pull/232

`mappings` is an array and therefore the `=` operator cannot be used there. I left it as is and open to discussion as indicated in the original PR mentioned above.

**Comment by chevalleyc** [comment]
@birgerhaarbrandt I suggest to merge this PR and eventually open a new CR regarding AQL query on array values (btw we have another pending issue related to error messages which apply to the above behavior)

**Comment by chevalleyc** [comment]
@birgerhaarbrandt to add to my comment above, AQL doesn't support (at least explicitly in both spec and grammar AFAIK) a 'IN' subselect operator as defined at https://www.postgresql.org/docs/9/functions-subquery.html#AEN16806. Perhaps ANY or SOME would be a better choice TBD. F.e. the expression on an array should be written as:

```

{
  "q": "SELECT c FROM EHR e CONTAINS COMPOSITION c WHERE 'Erfasst' IN c/context/setting/mappings/purpose/value" 
}
```
Or
```

{
  "q": "SELECT c FROM EHR e CONTAINS COMPOSITION c WHERE 'Erfasst' = ANY( c/context/setting/mappings/purpose/value)" 
}
```

**Comment by chevalleyc** [comment]
@birgerhaarbrandt  created a specific issue related to the WHERE case above (https://github.com/ehrbase/project_management/issues/404)

**Pull request merged**
