### PR TITLE
ensure json object is not iterated

### PR DESCRIPTION
**Pull request by chevalleyc**
## Changes

Fix an issue with json array iteration as it could fall on an non-iterable object.

## Related issue

Fixes: https://github.com/ehrbase/project_management/issues/506 (see comment in the issue re particular failing select item)

## Additional information and checks
- [ ] Pull request linked in changelog

### CODE REVIEW

**Comment by birgerhaarbrandt** [comment]
@chevalleyc Is this covered by an integration test in the SDK?

**Comment by chevalleyc** [comment]
> @chevalleyc Is this covered by an integration test in the SDK?

not yet... it is based on Pascal's Viro test suite. This one should be in the SDK test, but not there yet.

**Comment by birgerhaarbrandt** [comment]
@chevalleyc I would rather like to have this as part of the PR or in a ticket that is directly addressed next. What do you prefer?

**Comment by chevalleyc** [comment]
> @chevalleyc I would rather like to have this as part of the PR or in a ticket that is directly addressed next. What do you prefer?

I much prefer a separate ticket as editing tests is not practical at the moment and still cause issue with the sync feature

**Comment by birgerhaarbrandt** [comment]
I will create a separate ticket then

**Pull request merged**
