### PR TITLE
Feature/207 diff in category

### PR DESCRIPTION
**Pull request by chevalleyc**
## Changes
- AQL on composition category now returns the correct value (f.e. composition/category/value)

## Related issue
closes: https://github.com/ehrbase/project_management/issues/207

## Additional information and checks

- [x] Pull request linked in changelog

### CODE REVIEW

**Comment by testautomation** [comment]
Test shows some diffs. Use below actual vs. expected as input on http://jsondiff.com/ for a manual check or check my screenshot below.

@chevalleyc @ppazos is an update of test-data-set required now?

```
D-400 Execute Ad-HOc Query - Get Data :: Get Data related query.      
//////////// ACTUAL //////////////////////////////

{
    "q": "SELECT c/uid/value, c/name/value, c/archetype_node_id, c/language, c/territory, c/category/value FROM EHR e [ehr_id/value='0055ddfb-57b7-4a60-bb31-7c809d13c2f8'] CONTAINS COMPOSITION c",
    "columns": [
        {
            "path": "/uid/value",
            "name": "#0"
        },
        {
            "path": "/name/value",
            "name": "#1"
        },
        {
            "path": "/archetype_node_id",
            "name": "#2"
        },
        {
            "path": "/language",
            "name": "#3"
        },
        {
            "path": "/territory",
            "name": "#4"
        },
        {
            "path": "/category/value",
            "name": "#5"
        }
    ],
    "rows": [
        [
            "760f502c-a7aa-42b9-9e26-c0af975374ae::local.ehrbase.org::1",
            "Minimal",
            "openEHR-EHR-COMPOSITION.minimal.v1",
            {
                "_type": "CODE_PHRASE",
                "code_string": "en",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "ISO_639-1"
                }
            },
            {
                "_type": "CODE_PHRASE",
                "code_string": "UY",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "ISO_3166-1"
                }
            },
            "event"
        ],
        [
            "03d95f55-9435-4f98-8531-239909ccdb8d::local.ehrbase.org::1",
            "Minimal",
            "openEHR-EHR-COMPOSITION.minimal.v1",
            {
                "_type": "CODE_PHRASE",
                "code_string": "en",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "ISO_639-1"
                }
            },
            {
                "_type": "CODE_PHRASE",
                "code_string": "UY",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "ISO_3166-1"
                }
            },
            "event"
        ],
        [
            "48739f95-b8af-423c-bb28-05ce61e4584b::local.ehrbase.org::1",
            "Minimal",
            "openEHR-EHR-COMPOSITION.minimal.v1",
            {
                "_type": "CODE_PHRASE",
                "code_string": "en",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "ISO_639-1"
                }
            },
            {
                "_type": "CODE_PHRASE",
                "code_string": "UY",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "ISO_3166-1"
                }
            },
            "event"
        ],
        [
            "0db50c0a-061c-45d6-9098-8b5ebaadaade::local.ehrbase.org::1",
            "Minimal",
            "openEHR-EHR-COMPOSITION.minimal.v1",
            {
                "_type": "CODE_PHRASE",
                "code_string": "en",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "ISO_639-1"
                }
            },
            {
                "_type": "CODE_PHRASE",
                "code_string": "UY",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "ISO_3166-1"
                }
            },
            "event"
        ],
        [
            "9c93d212-c061-436e-86a2-365533eb8082::local.ehrbase.org::1",
            "Minimal",
            "openEHR-EHR-COMPOSITION.minimal.v1",
            {
                "_type": "CODE_PHRASE",
                "code_string": "en",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "ISO_639-1"
                }
            },
            {
                "_type": "CODE_PHRASE",
                "code_string": "UY",
                "terminology_id": {
                    "_type": "TERMINOLOGY_ID",
                    "value": "ISO_3166-1"
                }
            },
            "event"
        ]
    ]
}

/////////// EXPECTED //////////////////////////////

{
    "q": "SELECT c/uid/value, c/name/value, c/archetype_node_id, c/language, c/territory, c/category/value FROM EHR e [ehr_id/value='0055ddfb-57b7-4a60-bb31-7c809d13c2f8'] CONTAINS COMPOSITION c",
    "columns": [
        {
            "name": "#0",
            "path": "/uid/value"
        },
        {
            "name": "#1",
            "path": "/name/value"
        },
        {
            "name": "#2",
            "path": "/archetype_node_id"
        },
        {
            "name": "#3",
            "path": "/language"
        },
        {
            "name": "#4",
            "path": "/territory"
        },
        {
            "name": "#5",
            "path": "/category/value"
        }
    ],
    "rows": [
        [
            "760f502c-a7aa-42b9-9e26-c0af975374ae::local.ehrbase.org::1",
            "Minimal",
            "openEHR-EHR-COMPOSITION.minimal.v1",
            {
                "terminology_id": {
                    "value": "ISO_639-1"
                },
                "code_string": "en"
            },
            {
                "terminology_id": {
                    "value": "ISO_3166-1"
                },
                "code_string": "UY"
            },
            "event"
        ],
        [
            "48739f95-b8af-423c-bb28-05ce61e4584b::local.ehrbase.org::1",
            "Minimal",
            "openEHR-EHR-COMPOSITION.minimal.v1",
            {
                "terminology_id": {
                    "value": "ISO_639-1"
                },
                "code_string": "en"
            },
            {
                "terminology_id": {
                    "value": "ISO_3166-1"
                },
                "code_string": "UY"
            },
            "event"
        ],
        [
            "03d95f55-9435-4f98-8531-239909ccdb8d::local.ehrbase.org::1",
            "Minimal",
            "openEHR-EHR-COMPOSITION.minimal.v1",
            {
                "terminology_id": {
                    "value": "ISO_639-1"
                },
                "code_string": "en"
            },
            {
                "terminology_id": {
                    "value": "ISO_3166-1"
                },
                "code_string": "UY"
            },
            "event"
        ],
        [
            "0db50c0a-061c-45d6-9098-8b5ebaadaade::local.ehrbase.org::1",
            "Minimal",
            "openEHR-EHR-COMPOSITION.minimal.v1",
            {
                "terminology_id": {
                    "value": "ISO_639-1"
                },
                "code_string": "en"
            },
            {
                "terminology_id": {
                    "value": "ISO_3166-1"
                },
                "code_string": "UY"
            },
            "event"
        ],
        [
            "9c93d212-c061-436e-86a2-365533eb8082::local.ehrbase.org::1",
            "Minimal",
            "openEHR-EHR-COMPOSITION.minimal.v1",
            {
                "terminology_id": {
                    "value": "ISO_639-1"
                },
                "code_string": "en"
            },
            {
                "terminology_id": {
                    "value": "ISO_3166-1"
                },
                "code_string": "UY"
            },
            "event"
        ]
    ]
}
```
## jsondiff.com preview
image

**Review by ghost — CHANGES_REQUESTED** [review]
please check my [comment ](https://github.com/ehrbase/ehrbase/pull/209#issuecomment-607143330)@chevalleyc / @ppazos

**Comment by chevalleyc** [comment]
> Test shows some diffs. Use below actual vs. expected as input on http://jsondiff.com/ for a manual check or check my screenshot below.
> 
> @chevalleyc @ppazos is an update of test-data-set required now?
> 
> ```
> D-400 Execute Ad-HOc Query - Get Data :: Get Data related query.      
> //////////// ACTUAL //////////////////////////////
> 
> {
>     "q": "SELECT c/uid/value, c/name/value, c/archetype_node_id, c/language, c/territory, c/category/value FROM EHR e [ehr_id/value='0055ddfb-57b7-4a60-bb31-7c809d13c2f8'] CONTAINS COMPOSITION c",
>     "columns": [
>         {
>             "path": "/uid/value",
>             "name": "#0"
>         },
>         {
>             "path": "/name/value",
>             "name": "#1"
>         },
>         {
>             "path": "/archetype_node_id",
>             "name": "#2"
>         },
>         {
>             "path": "/language",
>             "name": "#3"
>         },
>         {
>             "path": "/territory",
>             "name": "#4"
>         },
>         {
>             "path": "/category/value",
>             "name": "#5"
>         }
>     ],
>     "rows": [
>         [
>             "760f502c-a7aa-42b9-9e26-c0af975374ae::local.ehrbase.org::1",
>             "Minimal",
>             "openEHR-EHR-COMPOSITION.minimal.v1",
>             {
>                 "_type": "CODE_PHRASE",
>                 "code_string": "en",
>                 "terminology_id": {
>                     "_type": "TERMINOLOGY_ID",
>                     "value": "ISO_639-1"
>                 }
>             },
>             {
>                 "_type": "CODE_PHRASE",
>                 "code_string": "UY",
>                 "terminology_id": {
>                     "_type": "TERMINOLOGY_ID",
>                     "value": "ISO_3166-1"
>                 }
>             },
>             "event"
>         ],
>         [
>             "03d95f55-9435-4f98-8531-239909ccdb8d::local.ehrbase.org::1",
>             "Minimal",
>             "openEHR-EHR-COMPOSITION.minimal.v1",
>             {
>                 "_type": "CODE_PHRASE",
>                 "code_string": "en",
>                 "terminology_id": {
>                     "_type": "TERMINOLOGY_ID",
>                     "value": "ISO_639-1"
>                 }
>             },
>             {
>                 "_type": "CODE_PHRASE",
>                 "code_string": "UY",
>                 "terminology_id": {
>                     "_type": "TERMINOLOGY_ID",
>                     "value": "ISO_3166-1"
>                 }
>             },
>             "event"
>         ],
>         [
>             "48739f95-b8af-423c-bb28-05ce61e4584b::local.ehrbase.org::1",
>             "Minimal",
>             "openEHR-EHR-COMPOSITION.minimal.v1",
>             {
>                 "_type": "CODE_PHRASE",
>                 "code_string": "en",
>                 "terminology_id": {
>                     "_type": "TERMINOLOGY_ID",
>                     "value": "ISO_639-1"
>                 }
>             },
>             {
>                 "_type": "CODE_PHRASE",
>                 "code_string": "UY",
>                 "terminology_id": {
>                     "_type": "TERMINOLOGY_ID",
>                     "value": "ISO_3166-1"
>                 }
>             },
>             "event"
>         ],
>         [
>             "0db50c0a-061c-45d6-9098-8b5ebaadaade::local.ehrbase.org::1",
>             "Minimal",
>             "openEHR-EHR-COMPOSITION.minimal.v1",
>             {
>                 "_type": "CODE_PHRASE",
>                 "code_string": "en",
>                 "terminology_id": {
>                     "_type": "TERMINOLOGY_ID",
>                     "value": "ISO_639-1"
>                 }
>             },
>             {
>                 "_type": "CODE_PHRASE",
>                 "code_string": "UY",
>                 "terminology_id": {
>                     "_type": "TERMINOLOGY_ID",
>                     "value": "ISO_3166-1"
>                 }
>             },
>             "event"
>         ],
>         [
>             "9c93d212-c061-436e-86a2-365533eb8082::local.ehrbase.org::1",
>             "Minimal",
>             "openEHR-EHR-COMPOSITION.minimal.v1",
>             {
>                 "_type": "CODE_PHRASE",
>                 "code_string": "en",
>                 "terminology_id": {
>                     "_type": "TERMINOLOGY_ID",
>                     "value": "ISO_639-1"
>                 }
>             },
>             {
>                 "_type": "CODE_PHRASE",
>                 "code_string": "UY",
>                 "terminology_id": {
>                     "_type": "TERMINOLOGY_ID",
>                     "value": "ISO_3166-1"
>                 }
>             },
>             "event"
>         ]
>     ]
> }
> 
> /////////// EXPECTED //////////////////////////////
> 
> {
>     "q": "SELECT c/uid/value, c/name/value, c/archetype_node_id, c/language, c/territory, c/category/value FROM EHR e [ehr_id/value='0055ddfb-57b7-4a60-bb31-7c809d13c2f8'] CONTAINS COMPOSITION c",
>     "columns": [
>         {
>             "name": "#0",
>             "path": "/uid/value"
>         },
>         {
>             "name": "#1",
>             "path": "/name/value"
>         },
>         {
>             "name": "#2",
>             "path": "/archetype_node_id"
>         },
>         {
>             "name": "#3",
>             "path": "/language"
>         },
>         {
>             "name": "#4",
>             "path": "/territory"
>         },
>         {
>             "name": "#5",
>             "path": "/category/value"
>         }
>     ],
>     "rows": [
>         [
>             "760f502c-a7aa-42b9-9e26-c0af975374ae::local.ehrbase.org::1",
>             "Minimal",
>             "openEHR-EHR-COMPOSITION.minimal.v1",
>             {
>                 "terminology_id": {
>                     "value": "ISO_639-1"
>                 },
>                 "code_string": "en"
>             },
>             {
>                 "terminology_id": {
>                     "value": "ISO_3166-1"
>                 },
>                 "code_string": "UY"
>             },
>             "event"
>         ],
>         [
>             "48739f95-b8af-423c-bb28-05ce61e4584b::local.ehrbase.org::1",
>             "Minimal",
>             "openEHR-EHR-COMPOSITION.minimal.v1",
>             {
>                 "terminology_id": {
>                     "value": "ISO_639-1"
>                 },
>                 "code_string": "en"
>             },
>             {
>                 "terminology_id": {
>                     "value": "ISO_3166-1"
>                 },
>                 "code_string": "UY"
>             },
>             "event"
>         ],
>         [
>             "03d95f55-9435-4f98-8531-239909ccdb8d::local.ehrbase.org::1",
>             "Minimal",
>             "openEHR-EHR-COMPOSITION.minimal.v1",
>             {
>                 "terminology_id": {
>                     "value": "ISO_639-1"
>                 },
>                 "code_string": "en"
>             },
>             {
>                 "terminology_id": {
>                     "value": "ISO_3166-1"
>                 },
>                 "code_string": "UY"
>             },
>             "event"
>         ],
>         [
>             "0db50c0a-061c-45d6-9098-8b5ebaadaade::local.ehrbase.org::1",
>             "Minimal",
>             "openEHR-EHR-COMPOSITION.minimal.v1",
>             {
>                 "terminology_id": {
>                     "value": "ISO_639-1"
>                 },
>                 "code_string": "en"
>             },
>             {
>                 "terminology_id": {
>                     "value": "ISO_3166-1"
>                 },
>                 "code_string": "UY"
>             },
>             "event"
>         ],
>         [
>             "9c93d212-c061-436e-86a2-365533eb8082::local.ehrbase.org::1",
>             "Minimal",
>             "openEHR-EHR-COMPOSITION.minimal.v1",
>             {
>                 "terminology_id": {
>                     "value": "ISO_639-1"
>                 },
>                 "code_string": "en"
>             },
>             {
>                 "terminology_id": {
>                     "value": "ISO_3166-1"
>                 },
>                 "code_string": "UY"
>             },
>             "event"
>         ]
>     ]
> }
> ```
> 
> ## jsondiff.com preview
> 
> image

Actually, the expected json are not complete since they miss the type specifications as required for canonical json. I would suggest to update the test_data_set accordingly. Anyway, the fix here is to address the issue for AQL querying on composition/category (which was previously returning erroneous values)

**Comment by ppazos** [comment]
@testautomation the data looks good, the difference is as @chevalleyc says: the one on the right is missing some _type attributes but that has to do on how the system outputs the JSON, not in the committed data.

I see the _type attributes are present in the composition data, though those are not required, since for compositon.language and composition.territory the types in the RM are always CODE_PHRASE, only on those cases the _type in the JSON is not required. Considering this, the result from the server is not "incorrect".

The real issue is we don't have that documented. We could choose between "always require _type for all nodes", or "require _type only when it's required". We need to define that somewhere. @Geisterfalle do you know if it's there any decision around this?

**Review by ghost — APPROVED** [review]

**Pull request merged**
