### PR TITLE
Feature/sync/737 value point paths

### PR DESCRIPTION
**Pull request by chevalleyc**
## Changes

- Identify actual AQL path for a given variable expression 
- Use node/name predicate whenever required (f.e. adhoc section identified by name)
- Assemble SQL unions based on actual templates used in DB entries (this is normally performed using an INDEX SCAN only)
- Eliminate path search branches whenever a path is not valid for a given template
- Code clean-up and refactoring
- Fixed proper handling of EXISTS whenever the path is not found for a template
- Fixed some minor issues impacting tests
- Factorize usage of lateral joins to deal with array elements

## Related issue

Fixes: https://github.com/ehrbase/ehrbase/issues/792
Fixes: https://github.com/ehrbase/ehrbase/issues/737
Fixes: https://github.com/ehrbase/ehrbase/issues/728
Fixes: https://github.com/ehrbase/ehrbase/issues/718
Fixes: https://github.com/ehrbase/ehrbase/issues/557

## Additional information and checks

- [ ] Pull request linked in changelog

### CODE REVIEW

**Comment by sidharthramesh** [comment]
Hey @chevalleyc. The following findings are tested at commit [3b1b056](https://github.com/ehrbase/ehrbase/pull/807/commits/3b1b056d1690eba1ab6b961ea7ffe40cc7c64de8).

@neutralboy @ATHULKNAIR
# Regarding #808

## Case 1.1: Works as expected
```json
{
  "q": "SELECT c as composition from EHR e CONTAINS COMPOSITION c CONTAINS INSTRUCTION i [openEHR-EHR-INSTRUCTION.medication_order.v3]"
}
```

## Case 1.2: Does not work
```json
{
  "q": "SELECT c as composition from EHR e CONTAINS COMPOSITION c CONTAINS INSTRUCTION i"
}
```

Result:
```json
{
	"error": "Bad Request",
	"message": "Could not process query/stored-query, reason: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0"
}
```

Expected: 200 OK

# Regarding #728 
## Setup: 
With template [vitagroup-medication-list.v0.txt](https://github.com/ehrbase/ehrbase/files/8488247/vitagroup-medication-list.v0.txt)
With EHR: 084b2586-6b5d-490a-99d3-57251e1b79fd
With composition:
```json
{
    "vitagroup-medication-list.v0/medication_order/order:0/medication_item": "Dolo",
    "vitagroup-medication-list.v0/medication_order/order:0/overall_directions_description": "1-1-1",
    "vitagroup-medication-list.v0/context/start_time": "2022-04-13T19:07:13.557Z",
    "vitagroup-medication-list.v0/context/setting|code": "238",
    "vitagroup-medication-list.v0/context/setting|value": "other care",
    "vitagroup-medication-list.v0/context/setting|terminology": "openehr",
    "vitagroup-medication-list.v0/medication_order/order:0/timing": "R1",
    "vitagroup-medication-list.v0/medication_order/order:0/timing|formalism": "timing",
    "vitagroup-medication-list.v0/medication_order/order:0/action_archetype_id": "/.*/",
    "vitagroup-medication-list.v0/medication_order/narrative": "<none>",
    "vitagroup-medication-list.v0/medication_order/language|code": "en",
    "vitagroup-medication-list.v0/medication_order/language|terminology": "ISO_639-1",
    "vitagroup-medication-list.v0/medication_order/encoding|code": "UTF-8",
    "vitagroup-medication-list.v0/medication_order/encoding|terminology": "IANA_character-sets",
    "vitagroup-medication-list.v0/category|code": "433",
    "vitagroup-medication-list.v0/category|terminology": "openehr",
    "vitagroup-medication-list.v0/category|value": "event",
    "vitagroup-medication-list.v0/language|terminology": "ISO_639-1",
    "vitagroup-medication-list.v0/language|code": "en",
    "vitagroup-medication-list.v0/territory|code": "IN",
    "vitagroup-medication-list.v0/territory|terminology": "ISO_3166-1",
    "vitagroup-medication-list.v0/composer|name": "Medblocks UI",
    "vitagroup-medication-list.v0/medication_order/order:1/medication_item": "Augmentin",
    "vitagroup-medication-list.v0/medication_order/order:1/overall_directions_description": "1-0-1"
}
```
## Case 2.1: Works as expected
Execute AQL
```json
{
  "q": "SELECT i/activities[at0001]/description[at0002]/items[at0070]/value/value as medication from EHR e CONTAINS COMPOSITION c CONTAINS INSTRUCTION i [openEHR-EHR-INSTRUCTION.medication_order.v3] where c/archetype_details/template_id/value MATCHES {'vitagroup-medication-list.v0'} AND e/ehr_id/value='084b2586-6b5d-490a-99d3-57251e1b79fd'"
}
```
returns 

```json
{
	"q": "SELECT i/activities[at0001]/description[at0002]/items[at0070]/value/value as medication from EHR e CONTAINS COMPOSITION c CONTAINS INSTRUCTION i [openEHR-EHR-INSTRUCTION.medication_order.v3] where c/archetype_details/template_id/value MATCHES {'vitagroup-medication-list.v0'} AND e/ehr_id/value='084b2586-6b5d-490a-99d3-57251e1b79fd'",
	"columns": [
		{
			"path": "/activities[at0001]/description[at0002]/items[at0070]/value/value",
			"name": "medication"
		}
	],
	"rows": [
		[
			"Dolo"
		],
		[
			"Augmentin"
		]
	]
}
```

## Case 2.2: Works, but incorrect?
Having another select (same as 2.1 but with additional path `i/activities[at0001]/description[at0002]/items[at0009]/value`:

```json
{
  "q": "SELECT i/activities[at0001]/description[at0002]/items[at0070]/value/value as medication, i/activities[at0001]/description[at0002]/items[at0009]/value as dosage from EHR e CONTAINS COMPOSITION c CONTAINS INSTRUCTION i [openEHR-EHR-INSTRUCTION.medication_order.v3] where c/archetype_details/template_id/value MATCHES {'vitagroup-medication-list.v0'} AND e/ehr_id/value='084b2586-6b5d-490a-99d3-57251e1b79fd'"
}
```
Return:
```json
{
	"q": "SELECT i/activities[at0001]/description[at0002]/items[at0070]/value/value as medication, i/activities[at0001]/description[at0002]/items[at0009]/value/value as dosage from EHR e CONTAINS COMPOSITION c CONTAINS INSTRUCTION i [openEHR-EHR-INSTRUCTION.medication_order.v3] where c/archetype_details/template_id/value MATCHES {'vitagroup-medication-list.v0'} AND e/ehr_id/value='084b2586-6b5d-490a-99d3-57251e1b79fd'",
	"columns": [
		{
			"path": "/activities[at0001]/description[at0002]/items[at0070]/value/value",
			"name": "medication"
		},
		{
			"path": "/activities[at0001]/description[at0002]/items[at0009]/value/value",
			"name": "dosage"
		}
	],
	"rows": [
		[
			"Dolo",
			"1-1-1"
		],
		[
			"Dolo",
			"1-0-1"
		],
		[
			"Augmentin",
			"1-1-1"
		],
		[
			"Augmentin",
			"1-0-1"
		]
	]
}
```

Each medication item is repeated twice. There is only 1 composition and the items appear only once in the composition.

Expected:
```json
{
	"q": "SELECT i/activities[at0001]/description[at0002]/items[at0070]/value/value as medication, i/activities[at0001]/description[at0002]/items[at0009]/value/value as dosage from EHR e CONTAINS COMPOSITION c CONTAINS INSTRUCTION i [openEHR-EHR-INSTRUCTION.medication_order.v3] where c/archetype_details/template_id/value MATCHES {'vitagroup-medication-list.v0'} AND e/ehr_id/value='084b2586-6b5d-490a-99d3-57251e1b79fd'",
	"columns": [
		{
			"path": "/activities[at0001]/description[at0002]/items[at0070]/value/value",
			"name": "medication"
		},
		{
			"path": "/activities[at0001]/description[at0002]/items[at0009]/value/value",
			"name": "dosage"
		}
	],
	"rows": [
		[
			"Dolo",
			"1-1-1"
		],
		[
			"Dolo",
			"1-0-1"
		]
	]
}
```

## Case 2.3: Works as expected
```json
{
  "q": "SELECT c/content[openEHR-EHR-INSTRUCTION.medication_order.v3]/activities[at0001]/description[at0002]/items[at0070]/value/value as medication from EHR e CONTAINS COMPOSITION c where c/archetype_details/template_id/value MATCHES {'vitagroup-medication-list.v0'} AND e/ehr_id/value='084b2586-6b5d-490a-99d3-57251e1b79fd'"
}
```
returns
```json
{
	"q": "SELECT c/content[openEHR-EHR-INSTRUCTION.medication_order.v3]/activities[at0001]/description[at0002]/items[at0070]/value/value as medication from EHR e CONTAINS COMPOSITION c where c/archetype_details/template_id/value MATCHES {'vitagroup-medication-list.v0'} AND e/ehr_id/value='084b2586-6b5d-490a-99d3-57251e1b79fd'",
	"columns": [
		{
			"path": "/content[openEHR-EHR-INSTRUCTION.medication_order.v3]/activities[at0001]/description[at0002]/items[at0070]/value/value",
			"name": "medication"
		}
	],
	"rows": [
		[
			"Dolo"
		],
		[
			"Augmentin"
		]
	]
}
```

## Case 2.4: Does not work
Selecting another value from the composition (same as 2.2 but with c/uid/value) when using path of repeated element from composition doesn't work
```json
{
  "q": "SELECT c/uid/value as uid, c/content[openEHR-EHR-INSTRUCTION.medication_order.v3]/activities[at0001]/description[at0002]/items[at0070]/value/value as medication from EHR e CONTAINS COMPOSITION c where c/archetype_details/template_id/value MATCHES {'vitagroup-medication-list.v0'} AND e/ehr_id/value='084b2586-6b5d-490a-99d3-57251e1b79fd'"
}
```

Result:
```json
{
	"error": "Bad Request",
	"message": "Could not perform SQL query:org.postgresql.util.PSQLException: ERROR: each UNION query must have the same number of columns\n  Position: 979, AQL expression:SELECTc/uid/valueasuid,c/content[openEHR-EHR-INSTRUCTION.medication_order.v3]/activities[at0001]/description[at0002]/items[at0070]/value/valueasmedicationfromEHReCONTAINSCOMPOSITIONcwherec/archetype_details/template_id/valueMATCHES{'vitagroup-medication-list.v0'}ANDe/ehr_id/value='084b2586-6b5d-490a-99d3-57251e1b79fd'<EOF>, Translated SQL:select jsonb_extract_path_text(cast(\"ehr\".\"js_composition\"(\n  cast(composition_join.id as uuid),\n  'local.ehrbase.org'\n) as jsonb),'uid','value') as \"uid\", array_2089617651_13.var_2089617651_14 as \"medication\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" join lateral (\n  select (ehr.xjsonb_array_elements((\"ehr\".\"entry\".\"entry\"#>>'{/composition[openEHR-EHR-COMPOSITION.medication_list.v1],/content[openEHR-EHR-INSTRUCTION.medication_order.v3],0,/activities,/activities[at0001]}')::jsonb)#>>'{/description[at0002],/items[at0070],0,/value,value}') \n AS var_2089617651_14) as \"array_2089617651_13\" on true where (\"ehr\".\"entry\".\"template_id\" = ? and (\"ehr\".\"entry\".\"template_id\" IN  ( 'vitagroup-medication-list.v0' )  AND \"ehr_join\".\"id\" = '084b2586-6b5d-490a-99d3-57251e1b79fd')) union select jsonb_extract_path_text(cast(\"ehr\".\"js_composition\"(\n  cast(composition_join.id as uuid),\n  'local.ehrbase.org'\n) as jsonb),'uid','value') as \"uid\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where (\"ehr\".\"entry\".\"template_id\" = ? and (\"ehr\".\"entry\".\"template_id\" IN  ( 'vitagroup-medication-list.v0' )  AND \"ehr_join\".\"id\" = '084b2586-6b5d-490a-99d3-57251e1b79fd')) union select jsonb_extract_path_text(cast(\"ehr\".\"js_composition\"(\n  cast(composition_join.id as uuid),\n  'local.ehrbase.org'\n) as jsonb),'uid','value') as \"uid\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where (\"ehr\".\"entry\".\"template_id\" = ? and (\"ehr\".\"entry\".\"template_id\" IN  ( 'vitagroup-medication-list.v0' )  AND \"ehr_join\".\"id\" = '084b2586-6b5d-490a-99d3-57251e1b79fd')) union select jsonb_extract_path_text(cast(\"ehr\".\"js_composition\"(\n  cast(composition_join.id as uuid),\n  'local.ehrbase.org'\n) as jsonb),'uid','value') as \"uid\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where (\"ehr\".\"entry\".\"template_id\" = ? and (\"ehr\".\"entry\".\"template_id\" IN  ( 'vitagroup-medication-list.v0' )  AND \"ehr_join\".\"id\" = '084b2586-6b5d-490a-99d3-57251e1b79fd')) union select jsonb_extract_path_text(cast(\"ehr\".\"js_composition\"(\n  cast(composition_join.id as uuid),\n  'local.ehrbase.org'\n) as jsonb),'uid','value') as \"uid\" from \"ehr\".\"entry\" right outer join \"ehr\".\"composition\" as \"composition_join\" on \"composition_join\".\"id\" = \"ehr\".\"entry\".\"composition_id\" right outer join \"ehr\".\"ehr\" as \"ehr_join\" on \"ehr_join\".\"id\" = \"composition_join\".\"ehr_id\" where (\"ehr\".\"entry\".\"template_id\" = ? and (\"ehr\".\"entry\".\"template_id\" IN  ( 'vitagroup-medication-list.v0' )  AND \"ehr_join\".\"id\" = '084b2586-6b5d-490a-99d3-57251e1b79fd'))"
}
```

Expected: 200 OK

**Comment by chevalleyc** [comment]
--> @sidharthramesh part `regarding CR #728` is actually a change request. The change is about handling of lateral joins when it is used with multiple variables.

**Comment by sidharthramesh** [comment]
Hey @chevalleyc,
I'm very worried about cases 2.2 and 2.4.

So for the demonstration application:

We ask the patient which all drugs they have taken today:
image

This is recorded in a single template where the Medication Management archetype repeats multiple times 0..*

And we show a Medication compliance chart that displays when a patient took a particular medication to the doctor.
image

Not returning all the archetypes correctly mean that we might receive incorrect information on when a patient took a certain drug (which is unsafe). Before this PR, it was only returning the first drug that the patient selected. Now it's showing the drugs, but the dosages get mixed up in a cartesian product (which is not as unsafe, but still an issue).

**Comment by chevalleyc** [comment]
@sidharthramesh you can use this new version of the PR (the failing test is due to an internal glitch with our CI...). These changes correctly deal with the issue you've mentioned above. Pls check. Many thanks again for your valuable contribution :-)

**Comment by sidharthramesh** [comment]
@chevalleyc Thank you!
I tested it today and these were my results:
Case 1.1: Works perfectly!
Case 1.2: Works perfectly!
Case 2.1: Works perfectly!
Case 2.2: Works perfectly!
Case 2.3: Works perfectly!
Case 2.4: Works perfectly!

Everything seems to work beautifully! Thank you again for the fix!

**Comment by chevalleyc** [comment]
@sidharthramesh thank you for your quick response. All the best!

**Comment by sidharthramesh** [comment]
@chevalleyc a question on using this fix on a live system with pre-existing data: Will the AQLs work correctly on the old data? Or should I do some manual migrations to make it work?

**Comment by chevalleyc** [comment]
@sidharthramesh this change doesn't impact the data representation. Only the AQL processing is changed here. HTH

**Comment by chevalleyc** [comment]
Some explanation about this PR at https://github.com/ehrbase/ehrbase/wiki/AQL-Path-Interpreter-Enhancements

**Comment by stefanspiska** [comment]
replaced by https://github.com/ehrbase/ehrbase/pull/1001

**Comment by vladislavploaia** [comment]
Hello All,
Regarding [#728](https://github.com/ehrbase/ehrbase/issues/728)
Case 2.1 - passed
{
  "q": "SELECT i/activities[at0001]/description[at0002]/items[at0070]/value/value as medication from EHR e CONTAINS COMPOSITION c CONTAINS INSTRUCTION i [openEHR-EHR-INSTRUCTION.medication_order.v3] where c/archetype_details/template_id/value MATCHES {'vitagroup-medication-list.v0'} AND e/ehr_id/value='4adee638-3dcb-4480-add8-e15d8f8cdb2a'"
}
image

Case 2.2 - passed
{
  "q": "SELECT i/activities[at0001]/description[at0002]/items[at0070]/value/value as medication, i/activities[at0001]/description[at0002]/items[at0009]/value/value as dosage from EHR e CONTAINS COMPOSITION c CONTAINS INSTRUCTION i [openEHR-EHR-INSTRUCTION.medication_order.v3] where c/archetype_details/template_id/value MATCHES {'vitagroup-medication-list.v0'} AND e/ehr_id/value='4adee638-3dcb-4480-add8-e15d8f8cdb2a'"
}
image

Case 2.3 - passed
{
  "q": "SELECT c/content[openEHR-EHR-INSTRUCTION.medication_order.v3]/activities[at0001]/description[at0002]/items[at0070]/value/value as medication from EHR e CONTAINS COMPOSITION c where c/archetype_details/template_id/value MATCHES {'vitagroup-medication-list.v0'} AND e/ehr_id/value='4adee638-3dcb-4480-add8-e15d8f8cdb2a'"
}
image

Case 2.4 - passed
{
  "q": "SELECT c/uid/value as uid, c/content[openEHR-EHR-INSTRUCTION.medication_order.v3]/activities[at0001]/description[at0002]/items[at0070]/value/value as medication from EHR e CONTAINS COMPOSITION c where c/archetype_details/template_id/value MATCHES {'vitagroup-medication-list.v0'} AND e/ehr_id/value='4adee638-3dcb-4480-add8-e15d8f8cdb2a'"
}
image
CC: @stefanspiska , @vidi42

**Comment by vladislavploaia** [comment]
To sum up, here is the status for this ticket, where several tickets were mentioned:
728 - passed
808 - passed
792 - passed
737 - passed
718 - passed
557 - passed

**Pull request closed without merging**
