### PR TITLE
Minor fixes and failing integration tests for ABAC

### PR DESCRIPTION
**Pull request by sidharthramesh**
## Changes

- Added integration tests to check if ABAC server is being called after every API call in c787bf7f5e82bef9eda1408c9bcef90d23097ce0
- Fixed the composition in the ABAC Integration test to commit (it was failing with 400)
- Fixed 500 internal server error when EHR does not have subject id with ABAC turned on in 6ede6f2
## Related issue
 #690

## Additional information and checks

The following tests are currently failing:
- GET EHR: Does not call ABAC server. Probably not secured with ABAC.
- GET COMPOSITION (here of deleted composition): Does not call ABAC server (maybe works as expected?)
- GET QUERY: Does not call ABAC server. Probably not secured with ABAC.
- GET QUERY WITH MULTIPLE EHRs AND TEMPLATES (incl. posting those): Does not call ABAC server. Probably not secured with ABAC.

- [ ] Pull request linked in changelog

### CODE REVIEW

**Comment by subigre** [comment]
Hi @sidharthramesh, many thanks for the PR.
I have fixed the remaining issues and pushed back to your branches.
Could you please try locally and squash your commits and mine into one single commit.

**Comment by sidharthramesh** [comment]
Hey @subigre, I've added a few comments. Especially regarding why you're doing `subjectId != null`. Integration tests are passing for me. And thank you for resetting the database before the test! I was doing this manually every time. 

Not sure why sonar-analysis is failing though. I'll squash the commits once we figure this out.

**Comment by stefanspiska** [comment]
@sidharthramesh  @subigre  please ignore the failing sonar. this is a known issue with external pull-request.

**Comment by subigre** [comment]
> Hey @subigre, I've added a few comments. Especially regarding why you're doing `subjectId != null`. Integration tests are passing for me. And thank you for resetting the database before the test! I was doing this manually every time.
> 
> Not sure why sonar-analysis is failing though. I'll squash the commits once we figure this out.

My mistake, I did the change to test and then forgot to rollback 😢 
I fixed it now

**Comment by sidharthramesh** [comment]
@subigre commits squashed and ready

**Review by subigre — APPROVED** [review]

**Comment by subigre** [comment]
Resolves #690

**Comment by subigre** [comment]
Congratulations  👍 
image

**Comment by sidharthramesh** [comment]
Did I just break those AQL tests?

**Comment by stefanspiska** [comment]
@sidharthramesh 
No. this Test suit sometimes need to be restarted. Because it pre-calculates this value for the result and puts them in the Cache of the ci. But then the Cache sometimes needs to be recalculated.

**Pull request merged**
