### PR TITLE
Fixes ehrscape compo uid

### PR DESCRIPTION
**Pull request by jakesmolka**
## Changes

- EhrScape UID fix

## Related issue

fixes https://github.com/ehrbase/ehrbase/issues/481

## Additional information and checks

- [x] Pull request linked in changelog

### CODE REVIEW

**Comment by jakesmolka** [comment]
One result from the failing tests is that it can't accept structures like this in folders anymore:

``` json
"items": [
        {
      		"id": {
      			"_type": "HIER_OBJECT_ID",
      			"value": "d936409e-901f-4994-8d33-ed104d460456"
      		},
      		"namespace": "my.system.id",
      		"type": "VERSIONED_COMPOSITION"
      	}
      ]
```

The thrown error:

> "Problem deserializing property 'id' (expected type: [simple type, class java.lang.Object]; actual type: `java.util.LinkedHashMap`), problem: argument type mismatch\n at [Source: (StringReader); line: 1, column: 32669] (through reference chain: com.nedap.archie.rm.directory.Folder[\"folders\"]->java.util.ArrayList[0]->com.nedap.archie.rm.directory.Folder[\"items\"]->java.util.ArrayList[0]->com.nedap.archie.rm.support.identification.ObjectRef[\"id\"])"

This particular case is invoked just by creating a folder. Code-wise this means the controller wants to map the input to an Archie `Folder`. There might be some EHRbase custom de-serialization code being applied here, but apart from that this is plain Archie and Spring Boot.

**Review by ppazos — APPROVED** [review]
This looks good @jakesmolka and fixes what I commented for https://github.com/ehrbase/ehrbase/pull/552#discussion_r677721081

**Comment by ppazos** [comment]
@jakesmolka from your comment and the error, it seems it comes from the Archie JSON parser, since the structure seems correct. Maybe, since OBJECT_REF has subclasses, the _type is needed there to be able to parse the correct type.

**Comment by jakesmolka** [comment]
@ppazos right! @subigre already fixed that in https://github.com/openEHR/archie/pull/338 and therefore the bump in the last commit :slightly_smiling_face:
The other problems seem to be results of the UID change though.

**Pull request merged**
