### PR TITLE
Feature/281 contains refactoring ns

### PR DESCRIPTION
**Pull request by chevalleyc**
## Changes
This is the DB side implementation to deal with new CONTAINS strategy (see http://docs.ehrbase.org/en/latest/03_development/02_technical_docs/index.html#new-contain-clause-resolution-strategy)

## Related issue
Optimization of CONTAINS resolution. 

## Additional information and checks

Requires changes in SDK in PR: https://github.com/ehrbase/openEHR_SDK/pull/54
- [ ] Pull request linked in changelog

### CODE REVIEW

**Comment by Geisterfalle** [comment]
Thanks for the update! When I execute the following query

```
{
  "q": "select a/uid/value
from EHR e
contains COMPOSITION a
contains (
    CLUSTER a_a[openEHR-EHR-CLUSTER.specimen.v1] and
    (CLUSTER a_b[openEHR-EHR-CLUSTER.laboratory_test_panel.v0] or
    CLUSTER a_c[openEHR-EHR-CLUSTER.rubbish.v0]))" 
}
```

I get an empty result set while I expect there to be two results. Without the parentheses, this should also be a non-empty result set according to the precedence order

```
{
  "q": "select a/uid/value
from EHR e
contains COMPOSITION a
contains (
    CLUSTER a_a[openEHR-EHR-CLUSTER.specimen.v1] and
    CLUSTER a_b[openEHR-EHR-CLUSTER.laboratory_test_panel.v0] or
    CLUSTER a_c[openEHR-EHR-CLUSTER.rubbish.v0])" 
}
```

**Comment by chevalleyc** [comment]
It seems that for expression in the form: `contains COMPOSITION a [openEHR-EHR-COMPOSITION.report-result.v1] contains OBSERVATION` the actual existence of an OBSERVATION contained in COMPOSITION is not performed. This is not correct.

**Comment by chevalleyc** [comment]
> Thanks for the update! When I execute the following query
> 
> ```
> {
>   "q": "select a/uid/value
> from EHR e
> contains COMPOSITION a
> contains (
>     CLUSTER a_a[openEHR-EHR-CLUSTER.specimen.v1] and
>     (CLUSTER a_b[openEHR-EHR-CLUSTER.laboratory_test_panel.v0] or
>     CLUSTER a_c[openEHR-EHR-CLUSTER.rubbish.v0]))" 
> }
> ```
> 
> I get an empty result set while I expect there to be two results. Without the parentheses, this should also be a non-empty result set according to the precedence order
> 
> ```
> {
>   "q": "select a/uid/value
> from EHR e
> contains COMPOSITION a
> contains (
>     CLUSTER a_a[openEHR-EHR-CLUSTER.specimen.v1] and
>     CLUSTER a_b[openEHR-EHR-CLUSTER.laboratory_test_panel.v0] or
>     CLUSTER a_c[openEHR-EHR-CLUSTER.rubbish.v0])" 
> }
> ```

These latest changes address this issue.

**Comment by Geisterfalle** [comment]
I checked and the examples above work fine now. However, when adding another "and"/"or" like 

```
{
  "q": "select a/uid/value
from EHR e
contains COMPOSITION a
contains (
    CLUSTER a_a[openEHR-EHR-CLUSTER.specimen.v1] or
    (CLUSTER a_b[openEHR-EHR-CLUSTER.laboratory_test_panel.v0] and
    CLUSTER a_c[openEHR-EHR-CLUSTER.rubbish.v0]) or CLUSTER a_d[openEHR-EHR-CLUSTER.rubbish.v0] )" 
} 
```

I get the following error message

```
{
    "error": "Could not process query, reason:java.lang.IllegalStateException: Cannot apply operator on empty initial set",
    "status": "Bad Request"
}
```

**Comment by chevalleyc** [comment]
Fixed the change request above, and did multiple merges (incl. SDK)

**Pull request merged**
