### PR TITLE
fixed unproper formatting for time/value and origin/value

### PR DESCRIPTION
**Pull request by chevalleyc**
## Changes

Handle time/value and origin/value AQL query properly.

## Related issue
Fixes: https://github.com/ehrbase/project_management/issues/208#issuecomment-686615420

## Additional information and checks

- [ ] Pull request linked in changelog

### CODE REVIEW

**Comment by wlad** [comment]
I've rebuild ehrbase and rerun the test. The result is the same as reported in https://github.com/ehrbase/project_management/issues/208#issuecomment-686615420

```
D-500 Execute Ad-HOc Query - Get Data :: Get Data related query.      
//////////// ACTUAL //////////////////////////////

{
    "q": "SELECT c/uid/value, o/name/value, o/data[at0001]/origin/value, o/data[at0001]/events[at0002]/time/value, o/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/value FROM EHR e [ehr_id/value='dff99269-ab03-402d-b361-6f64914b91c2'] CONTAINS COMPOSITION c [openEHR-EHR-COMPOSITION.minimal.v1] CONTAINS OBSERVATION o [openEHR-EHR-OBSERVATION.minimal.v1]",
    "columns": [
        {
            "path": "/uid/value",
            "name": "#0"
        },
        {
            "path": "/name/value",
            "name": "#1"
        },
        {
            "path": "/data[at0001]/origin/value",
            "name": "#2"
        },
        {
            "path": "/data[at0001]/events[at0002]/time/value",
            "name": "#3"
        },
        {
            "path": "/data[at0001]/events[at0002]/data[at0003]/items[at0004]/value/value",
            "name": "#4"
        }
    ],
    "rows": [
        [
            "aa41879b-991d-41c5-9bcb-b7e76da32828::local.ehrbase.org::1",
            "Minimal",
            {
                "value": "2019-01-28T21:22:19.552Z",
                "epoch_offset": 1548710539.0
            },
            "{\"value\": \"2019-01-28T21:22:19.562Z\", \"epoch_offset\": 1548710539}",
            "first value"
        ]
    ]
}
```

**Review by wlad — CHANGES_REQUESTED** [review]
s. last comment

**Comment by chevalleyc** [comment]
Seems like a regression to me, since I have explicitly tested this before pushing it. Just wondering if the migration has been successfully applied. I will retest that tomorrow on a fresh DB.

**Review by wlad — APPROVED** [review]
Sorry for false alarm! Seems some conflict with an old branch feature/208... happend on my local. Retest PASS after a fresh clone of repo!

**Pull request merged**
