### PR TITLE
Expanding creating compositions tests (conformance testing)

### PR DESCRIPTION
**Pull request by ndanilin**
##Changes

1. New universal keywords for composition have been added:
1.1 "commit composition"
1.2 "check the successful result of commit composition"
1.3 "check status_code of commit composition"

2. The same type of composition for different formats has been generated. They are in relevant format folders ("robot\_resources\test_data_sets\compositions\*")

3. The "COMPOSITION_TESTS\CREATE_COMPOSITION" section has been redesigned:
3.1 all tests with the ".x" prefix have been dropped
3.2 the other tests have been switched on new keywords and expanded by all formats
3.3 the checking of "ETag" and "Location" headers has been added

4. Tests with "FLAT", "TDD", "STRUCTURED" formats have been marked with a "future" tag because EhrBase don't support them yet

5. We ran all tests from a section "COMPOSITION_TESTS" on your stand EhrBase with a version 0.16.5. The regress has not been detected

6. In the EHR_COMPOSITON.md, we have added tables with test data combinations in other formats.

7. We have updated test case steps to link them to the table of data sets.

8. There have been added the link to the table in the precondition.

##Notes:

1. EhrBase doesn't support a section "links" in the body of composition yet (return status_code 500).
We added temporary composition examples with the "_full_without_links" postfix. It's recommended to switch tests on files with the "_full" postfix after your implementation

2. EhrBase doesn't return the "context" section in the persistent-composition response. But this logic isn't in the last version of the OpenEHR specification.
It's recommended to uncomment the relevant code in the keyword "check the successful result of commit composition" after your implementation

3. It seems to us that EhrBase returns a wrong value in the "Location" header.
In the OpenEHR specification the "Location" header must start with {baseUrl} and finish with {UUID::system_id::version} but EhrBase returns {ipv6 addres} and {UUID without system_id and version}.
It's recommended to uncomment the relevant code in the keyword "check the successful result of commit composition" after your implementation.

### CODE REVIEW

**Review by wlad — CHANGES_REQUESTED** [review]
@ndanilin @Nataliya21 technically the updated tests and the new composition keywords look great and execution passes locally (I've run `robot -i composition_create -e future robot/COMPOSITION_TESTS`)

1. New universal keywords for composition have been added :heavy_check_mark:
2. The same type of composition for different formats has been generated :heavy_check_mark:
3. The "COMPOSITION_TESTS\CREATE_COMPOSITION" section has been redesigned :heavy_check_mark:
4. Tests with "FLAT", "TDD", "STRUCTURED" formats have been marked with a "future" tag :heavy_check_mark:

Really great work! Thanks for this PR!


**A few minor/cosmetic issues I have to remark, though.**
1. Please leave the copyright notes in the files. We agreed at the start of this project to maintain copyright notes on a per file basis. Of course feel free to add your names at the top of the files you edit or create.
2. Please remove all files from the PR that you have not actively edited. For example most .md files seem to have been modified automatically by your git (this probably happend because of different handling of line endings between Linux and Windows). Also the image files, please remove from PR if you haven't modified them. You can find related files in "Files changes" section of PR 
image

3. In EHR_COMPOSITION.md it is hard to see what you actually modified. Im fine if @ppazos can review the file in this way but I guess better it would be to configure your git so that only relevant changes are displayed in PR.
4. Please resolve merge conflict (may be just needs to be synced with upstream repo)

**Review by ppazos — CHANGES_REQUESTED** [review]
@ndanilin conformance testing should verify just with one format, the openEHR API default is the canonical JSON, that is the one we test. IMO test with other formats is for integration testing, though the functionality is the same the purpose is different.

The docs should be removed from the PR.

**Comment by ndanilin** [comment]
@wlad, @ppazos
Thanks a lot for your detailed notes and comments.
1. Have returned the copyright notes
2. Have deleted the "doc\conformance_testing" folder from our branch. It led to the following corrections:
	2.1 have been removed all files that we have not actively edited
	2.2 have been resolved merge conflicts

**Comment by wlad** [comment]
:thinking:   strange ... but luckily the docs were not deleted and so there was  no need to copy any files around :sweat_smile:

**Comment by ndanilin** [comment]
@wlad 
Thank you for your help. 
In the beginning, there wasn't the conformance_testing folder in my branch. 
I thought GitHub would do a smart merge and this folder would remain from the upstream repo.
And it happened :smiley:

But you may be right, and in the future, I should sync my repo with the upstream repo, and then offer you our merge request.

**Comment by ppazos** [comment]
@wlad I see the pr was merged. Did you verified the validity of the data sets? I don't know how those were generated.

**Comment by wlad** [comment]
@ppazos sorry, totally forgot about that. Can you please check them. All the new datasets are in the subfolder https://github.com/ehrbase/ehrbase/tree/develop/tests/robot/_resources/test_data_sets/compositions
image

**Pull request merged**
